In [1]:
import numpy as np

In [9]:
arr=np.array([1,2,3,4])
sq_arr=np.sqrt(arr)
print(np.exp(arr))
print(np.log(arr))

[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]


In [13]:
angles=np.array([0, np.pi/2, np.pi])
print(angles)
print(np.sin(angles))
print(np.cos(angles))
print(np.tan(angles))

[0.         1.57079633 3.14159265 6.28318531 6.28318531]
[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -2.4492936e-16
 -2.4492936e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00  1.000000e+00  1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16 -2.44929360e-16
 -2.44929360e-16]


In [14]:
# log and e are inverse of each other. They get cancelled
print(np.log(np.array([1, np.e, np.e**2])))

[0. 1. 2.]


In [15]:
np.array([[1], [2], [3]]).shape

(3, 1)

In [36]:
a = np.array([[1], [2], [3]])   # shape (3, 1)
b = np.array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])       # shape (10,) -> treated as (1, 10)

print(a + b)

[[11 16 21 26 31 36 41 46 51 56 61]
 [12 17 22 27 32 37 42 47 52 57 62]
 [13 18 23 28 33 38 43 48 53 58 63]]


In [23]:
print(b[0])
print(b[-1])
print(b[b>12])

10
30
[20 30]


In [34]:
# Fancy indexing
print(b[[0,2,4]])

[10 30 50]


In [37]:
print(b[b%2==0])

[10 20 30 40 50 60]


In [41]:
arr_3d = np.zeros((2, 3, 4))

print(arr_3d.shape)

(2, 3, 4)


In [43]:
print(np.random.randint(1,10, size=(5,)))

[8 4 6 4 6]


In [44]:
arr = np.array([1,2,3,4,5])
np.exp(arr[0])

np.float64(2.718281828459045)

In [46]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate([a, b], axis=0//1)

array([1, 2, 3, 4, 5, 6])

In [47]:
user_string = input("Enter numbers separated by spaces: ")
arr_1d = np.fromstring(user_string, dtype=int, sep=' ')

print("Your 1D Array:", arr_1d)

Enter numbers separated by spaces:  1 2 3 4 5 6 7 8 9 0


Your 1D Array: [1 2 3 4 5 6 7 8 9 0]


In [56]:
arr = np.array([1, 2, 3, 4, 5])

print(arr[[0,2,4]].base)

None


In [61]:
def double_first_three(data):
    part = data[:3].copy()
    part *= 2
    print(part)
double_first_three(np.array([1, 2, 3, 4, 5]))

[2 4 6]


In [63]:
np.random.seed(42)
print(np.random.randint(1, 100, 3))  # Will always output [52 93 15]

[52 93 15]


In [4]:
# 1. Enter the left-hand numbers: [[1, 2], [3, 4]]
A = np.array([[1, 2], [3, 4]])

# 2. Enter the right-hand totals: [5, 11]
b = np.array([5, 11])

# 3. Solve for x and y
solution = np.linalg.solve(A, b)
print(solution)

[[1. 2.]]


In [1]:
import numpy as np
#5d MATRIX
# Method A: Create a 5D array of zeros
# Shape: 2x2x3x4x5 (Total elements = 2*2*3*4*5 = 240)
#array_zeros = np.zeros((2, 2, 3, 4, 5))

# Method B: Reshape sequential numbers into 5D
# Total elements must match the product of dimensions (2*2*2*2*2 = 32)
array_sequential = np.arange(54).reshape((3, 3, 3, 1, 2))
print(array_sequential)

[[[[[ 0  1]]

   [[ 2  3]]

   [[ 4  5]]]


  [[[ 6  7]]

   [[ 8  9]]

   [[10 11]]]


  [[[12 13]]

   [[14 15]]

   [[16 17]]]]



 [[[[18 19]]

   [[20 21]]

   [[22 23]]]


  [[[24 25]]

   [[26 27]]

   [[28 29]]]


  [[[30 31]]

   [[32 33]]

   [[34 35]]]]



 [[[[36 37]]

   [[38 39]]

   [[40 41]]]


  [[[42 43]]

   [[44 45]]

   [[46 47]]]


  [[[48 49]]

   [[50 51]]

   [[52 53]]]]]


In [2]:
a = np.array([[1], [2], [3]])   # shape (3, 1)
b = np.array([[10, 20, 30]])    # shape (1, 3)
print(a + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]
