In [1]:
import numpy as np


PATTERN ARRAY

In [2]:
ones_array = np.ones((5,5))


In [3]:
zero_array = np.zeros((3,3))

In [4]:
zero_array[1,1] = 9

In [5]:
print(zero_array)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [6]:
ones_array[1:4, 1:4]=zero_array

In [7]:
print(ones_array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
