In [1]:
import numpy as np

Basics

In [5]:
a = np.array([1, 2, 3])
b = np.array([4.0, 5.4, 6.9])
print(a)


[1 2 3]


In [9]:
print(b)

[4.  5.4 6.9]


In [12]:
print(a*b)

[ 4.  10.8 20.7]


In [33]:
# 0-D
a=np.array(11)
a.ndim

0

In [63]:
#1-D
a=np.array([1.8,2,3])
a.dtype

dtype('int16')

In [28]:
#2-D
a=np.array([[1,2,3],[4,5,6]])
a.ndim

2

In [56]:
#3-D
a=np.array([[[1,2,3],[5,6,7],[8,9,10]],[[11,22,33],[44,55,66],[77,88,99]]])
a.ndim

3

In [54]:
# Get shape
print(a)
a.shape

[1 2 3]


(3,)

In [47]:
# Get type
a.dtype

dtype('int16')

In [52]:
# Get size
a.itemsize

8

In [57]:
a.size

18

In [100]:
a=np.array([1,"hello",12.89],dtype='U16')
print(a)
a.ndim
a.dtype

['1' 'hello' '12.89']


dtype('<U16')

In [59]:
arr1=np.array([1,23,45])
arr2=np.array([45,78,12])
print(arr1+arr2)

[ 46 101  57]


In [71]:
# Zero matrix
zero_matrix = np.zeros((3,1))
print(zero_matrix)

[[0.]
 [0.]
 [0.]]


In [77]:
# Matrix with all ones
print(np.ones((1,3)))

[[1. 1. 1.]]


In [80]:
#Empty array containing garbage values
print(np.empty((2,1)))

[[9.9e-324]
 [1.5e-323]]


In [86]:
#1-D array like a loop
print(np.arange(0,40,2))

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


In [89]:
#1-D array like a loop
#print(np.arange(0,40,2).reshape(4,5))
print(np.reshape(np.arange(12)),(3,4))


[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]]


TypeError: reshape() missing 1 required positional argument: 'shape'

In [90]:
import numpy as np

# We create an Unsigned array (uint8) with 4 numbers
unsigned_array = np.array([0, 127, 128, 255], dtype=np.uint8)

# We tell NumPy to look at the EXACT same memory using the Signed rule (int8)
signed_array = unsigned_array.view(np.int8)

print("Unsigned (uint8):", unsigned_array)
print("Signed (int8)  :", signed_array)

Unsigned (uint8): [  0 127 128 255]
Signed (int8)  : [   0  127 -128   -1]


In [96]:
# numbers to be generated which are evenly spaced
print(np.linspace(0,1,6))

[0.  0.2 0.4 0.6 0.8 1. ]


In [109]:
print(np.full((4,6),7))

[[7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]]


In [110]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [116]:
print(np.random.rand(3,1))

[[0.3218069 ]
 [0.55162738]
 [0.48332219]]


In [119]:
print(np.random.randint(1,6, size=(2,1)))

[[2]
 [5]]


Array Operations

In [121]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [127]:
#Arithmetic operations
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(b//a)
print(a>2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[4 2 2]
[False False  True]


In [145]:
# Dot product
x = np.array([1, 2, 3])
y = np.array([1, 2, 3])
print(x*y)
print(np.dot(x,y))

[1 4 9]
14


In [141]:
# Statistics
print(x.sum())
print("Mean",x.mean())
print("Min: ", x.min())
print("Max: ", x.max())
print("Std dev: ", x.std())
print("Variance: ",x.var())
m=np.array([[1,2,3],[4,5,6]])
print("Reshaped version: ", m.reshape(3,2))

print("Transpose:\n ", m.T)

6
Mean 2.0
Min:  1
Max:  3
Std dev:  0.816496580927726
Variance:  0.6666666666666666
Reshaped version:  [[1 2]
 [3 4]
 [5 6]]
Transpose:
  [[1 4]
 [2 5]
 [3 6]]


In [146]:
# function for element equality
print(np.array_equal(x,y))


True


In [147]:
def cube_vectorized(arr):
    return arr ** 3
cube_vectorized(np.array([1,2,3,4]))

array([ 1,  8, 27, 64])